### ISSUE TITLE
Set openssl reliant features behind openssl feature flag. 

### ISSUE THREAD

**Issue by DGonzalezVillal** [virtee/snphost#8]
Can't compile code if OpenSSL 3.0 isn't installed and certain functionalities do not require OpenSSL. We should set features that are reliant on OpenSSL  behind a feature flag so that the tool can compile when verify features aren't wanted on snphost.

**Comment by tylerfanelli** [comment]
Sure, this sounds like a good idea. Will submit a PR.

**Comment by rikonor** [comment]
Would it be possible to publish static builds of `snphost`? That would at least allow one to side-step needing to compile.

**Comment by rikonor** [comment]
It seems that the `sev` crate now also has a `crypto_nossl` feature, which can be used to not require openssl. I did just try updating my local copy of `snphost` such that it points to:
```
sev = { version = "2.0.2", features = [ "crypto_nossl" ] }
```
and it indeed built without issue.
